### PR TITLE
Refactor search retry to use iterative approach

### PR DESCRIPTION
**Pull request by jsoriano**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Is iterative Vs recursive enforced by Go community?

**Comment by mdelapenya** [comment]
Related? https://twitter.com/rakyll/status/1177362139629047808?s=09

**Comment by jsoriano** [comment]
> Is iterative Vs recursive enforced by Go community?

No, it is not, I only find it more suitable for this case.

**Comment by jsoriano** [comment]
@mdelapenya I think it breaks tests as it doesn't wait the 20 seconds, I am working on a fix for this.

**Pull request merged**
